### ISSUE TITLE
[GUI] Resizing of window

### ISSUE THREAD

**Issue by p2004a** [Dezorganizacja/bridge#11]
Zwiększanie i zmniejszanie rozmiaru okienka w każdym miejscu nie zachowuje proporcji to jest, obiekty które zawsze powinny być wycentrowane nie są. Jestem w stanie takrze zmniejszyć okienko do takiego stopnia, że kontrolki zaczynaja znikać.

**Comment by knight-erraunt** [comment]
I am no GUI man!

**Comment by Larhard** [comment]
Poprawione
